### ISSUE TITLE
Base/Model.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-cijeomah/simpleorm#3]
/**
     \* Save model to the database or update model in Database.
     *
     \* @return boolean
     */
    public function save()
    {
        if($this->validate() === false) {
            return false;
        }
        if($this->exists()) {
            $run = $this->executeUpdateQuery();
        } else{
            $run = $this->executeInsertQuery();
        }
        return $run;
    }

... just use a not `!` instead of comparing it to false

**Comment by ghost** [comment]
This issue has been fixed
