### ISSUE TITLE
Database.php

### ISSUE THREAD

**Issue by unicodeveloper** [andela-cijeomah/simpleorm#4]
You should be writing atomic methods as much as possible. The `getInstance` method is doing too much, loading of environment variables should be done solely in another method and called in the getInstance method.

Convert `tabs` to `spaces` and use 4 spaces. Your indentation is just looking off. You shouldn't be having this issue at this stage.

Also your imports should be from shortest to longest

**Comment by ghost** [comment]
This issue has been fixed
